[package]
name = "trunk"
version = "0.0.1-alpha.1"
edition = "2021"
authors = ["Steven Miller"]
description = "A package manager for PostgreSQL extensions"
homepage = "https://trnk.io"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/coredb-io/trunk"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
