---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-issuer" (include "tembo-pod-init.fullname" .) }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-certificate" (include "tembo-pod-init.fullname" .) }}
  namespace: {{ template "tembo-pod-init.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
{{ include "tembo-pod-init-helm.labels" . | indent 4 }}
spec:
  dnsNames:
  - {{ printf "%s.%s.svc" (include "tembo-pod-init.fullname" .) (include "tembo-pod-init.namespace" .) }}
  - {{ printf "%s.%s.svc.cluster.local" (include "tembo-pod-init.fullname" .) (include "tembo-pod-init.namespace" .) }}
  issuerRef:
    name: {{ printf "%s-issuer" (include "tembo-pod-init.fullname" .) }}
  secretName: {{ printf "%s-tls" (include "tembo-pod-init.fullname" .) }}

