apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reconciler.serviceAccountName" . }}
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
