name: PGX builder images

on:
  pull_request:
    paths:
    - '.github/workflows/images.yaml'
    - '.github/actions/build-and-push-to-quay/**'
    - 'images/pgx-builder/**'
  push:
    branches:
      - 'main'

jobs:
  build_and_push_images:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_version:
          - "15"
          - "14"
        pgx_version:
          - "0.7.1"
          - "0.7.2"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Determine which tags to publish
        id: tags
        run: |
          set -xe
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [ "${BRANCH_NAME}" == "main" ]; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi
          SUFFIX="pg${{ matrix.pg_version }}-pgx${{ matrix.pgx_version }}"
          echo "suffix=${SUFFIX}" >> $GITHUB_OUTPUT
      - name: Build and upload image
        uses: ./.github/actions/build-and-push-to-quay
        with:
          image_name: pgx-builder
          docker_directory: ./images/pgx-builder
          publish_latest: false
          publish_calver: true
          push: ${{ steps.tags.outputs.push == 'true' }}
          tags: ${{ steps.tags.outputs.suffix }}
          calver_suffix: "-${{ steps.tags.outputs.suffix }}"
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
