name: CoreDB operator image build and upload

on:
  push:
    branches:
      - 'release/2023.1.27'
    paths:
    - 'coredb-operator/**'
    - '.github/workflows/publish_operator.yml'

jobs:
  push_to_registry:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and upload operator image
        uses: ./.github/actions/build-and-push-to-quay
        with:
          image_name: coredb-operator
          publish_latest: false
          publish_calver: false
          tags: 2023.1.27
          docker_directory: ./coredb-operator
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
