name: Reconciler image build and upload

on:
  push:
    branches:
      - main
    paths:
    - 'reconciler/**'
    - '.github/workflows/reconciler-deploy.yml'

jobs:
  push_to_registry:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check out the coredb repo to reuse some actions
        uses: actions/checkout@v3
        with:
          repository: coredb-io/coredb
          path: ./coredb
          ref: release/2023.1.27
      - name: Build and upload operator image
        uses: ./coredb/.github/actions/build-and-push-to-quay
        with:
          image_name: reconciler
          publish_latest: true
          publish_calver: true
          docker_directory: ./reconciler
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
